# log dir
log_dir: ./zhiyuanyan/logs/benchv2/icml25/release

# model setting
pretrained: 'no need to provide this for the effort model'
model_name: lora2
backbone_name: vit

# Non-VAE control. Change perturbation_name for each run and keep other settings unchanged.
perturbation_name: blur
perturbation_candidates:
  blur:
    type: blur
    kernel_size: 5
    sigma: 1.0
  noise:
    type: noise
    noise_std: 0.05
  sharpen:
    type: sharpen
    kernel_size: 5
    sigma: 1.0
    sharpen_amount: 1.0

# backbone setting
backbone_config:
  mode: original
  num_classes: 2
  inc: 3
  dropout: false

# dataset
all_dataset: [FaceForensics++, FF-F2F, FF-DF, FF-FS, FF-NT, FaceShifter, DeepFakeDetection, Celeb-DF-v1, Celeb-DF-v2, DFDCP, DFDC, DeeperForensics-1.0, UADFV]
train_dataset: [FaceForensics++]
test_dataset: [Celeb-DF-v2, DFDCP, DFDC]

compression: c23
train_batchSize: 16
test_batchSize: 16
workers: 8
frame_num: {'train': 8, 'test': 32}
resolution: 224
with_mask: false
with_landmark: false

# data augmentation
use_data_augmentation: true
data_aug:
  flip_prob: 0.5
  rotate_prob: 0.5
  rotate_limit: [-10, 10]
  blur_prob: 0.5
  blur_limit: [3, 7]
  brightness_prob: 0.5
  brightness_limit: [-0.1, 0.1]
  contrast_limit: [-0.1, 0.1]
  quality_lower: 40
  quality_upper: 100

# mean and std for normalization
mean: [0.48145466, 0.4578275, 0.40821073]
std: [0.26862954, 0.26130258, 0.27577711]

# optimizer config
optimizer:
  type: adam
  adam:
    lr: 0.0002
    beta1: 0.9
    beta2: 0.999
    eps: 0.00000001
    weight_decay: 0.0005
    amsgrad: false
  sgd:
    lr: 0.0002
    momentum: 0.9
    weight_decay: 0.0005

# training config
lr_scheduler: null
nEpochs: 30
start_epoch: 0
save_epoch: 1
rec_iter: 100
logdir: ./logs
manualSeed: 1024
save_ckpt: true
save_feat: true

# loss function
loss_func: cross_entropy
losstype: null

# metric
metric_scoring: auc

# cuda
ngpu: 1
cuda: true
cudnn: true

save_avg: true
